/IronFilter/det/setFilterCellSpacing 86.0 cm #76.0 cm
/IronFilter/det/setPolyHeight 50.0 cm
/IronFilter/det/setMultiplierLeadHeightFront 15.0 cm
/IronFilter/det/setModeratorAluminumHeight 30 cm
/IronFilter/det/setModeratorTitaniumHeight 5.0 cm # to get the DT position add the number till here
/IronFilter/det/setMultiplierLeadHeightRear 20.0 cm
/IronFilter/det/setMultiplierLeadRadius 20.0 cm
/IronFilter/det/setModeratorAluminumRadius 15.0 cm
/IronFilter/det/setModeratorTitaniumRadius 15.0 cm
/IronFilter/det/setTestX 0 m
/IronFilter/det/setTestY 0 m
/IronFilter/det/setTestZ 0 m

/run/initialize
/tracking/verbose 0

/control/getEnv a
/control/getEnv b

/random/setSeeds {a} {b}

/IronFilterDTGenerator/FileNumber 0
/IronFilterDTGenerator/TotalEvent 158680

/process/list
/run/printProgress 100000

/filename/setFilename DTFridgelab_0.root

/run/beamOn 158680 #geom57
